package Interface;


import Controller.Application;
import Controller.Configuration.Parameter;
import Controller.Controller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author corentin
 */
public class OptionPage extends javax.swing.JFrame {
    private Controller c;

    /**
     * Creates new form OptionPage
     */
    public OptionPage(Controller c) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        this.c = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PseudoField = new javax.swing.JTextField();
        PseudoCheckBttn = new javax.swing.JButton();
        AlreadyTakenNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HistoryPath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HistoryServerIP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RemoteIP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChangeConsideredAtReboot = new javax.swing.JLabel();
        RemoteMode = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        setTitle("ClavardApp - Paramètres");
        setResizable(false);

        jLabel2.setText("Pseudo de session");

        PseudoField.setText("Pseudo");
        PseudoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoFieldActionPerformed(evt);
            }
        });

        PseudoCheckBttn.setText("Vérifier");
        PseudoCheckBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoCheckBttnActionPerformed(evt);
            }
        });

        AlreadyTakenNameLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AlreadyTakenNameLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));
        AlreadyTakenNameLabel.setText("\"Pseudo\" est déjà pris");

        jLabel3.setText("Lien de sauvegarde de l'historique");

        HistoryPath.setText("Valeur par défaut");
        HistoryPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryPathActionPerformed(evt);
            }
        });

        jLabel4.setText("Adresse IP du serveur d'historique distant");

        HistoryServerIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryServerIPActionPerformed(evt);
            }
        });

        jLabel5.setText("Adresse IP du serveur distant");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Historique");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Pseudo");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setText("Mode distant");

        ChangeConsideredAtReboot.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ChangeConsideredAtReboot.setForeground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));
        ChangeConsideredAtReboot.setText("Ces changements prendront effet au redémarrage");

        RemoteMode.setText("Mode distant");
        RemoteMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoteModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(ChangeConsideredAtReboot)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(RemoteIP, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RemoteMode)
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(AlreadyTakenNameLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(PseudoField, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PseudoCheckBttn))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HistoryPath, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HistoryServerIP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PseudoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PseudoCheckBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlreadyTakenNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoteIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoteMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangeConsideredAtReboot)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Options");

        Save.setText("Enregistrer");
        Save.setMargin(new java.awt.Insets(0, 10, 0, 10));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PseudoCheckBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoCheckBttnActionPerformed
        // TODO add your handling code here:
        this.changePseudo();
    }//GEN-LAST:event_PseudoCheckBttnActionPerformed

    private void HistoryPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryPathActionPerformed

    private void PseudoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoFieldActionPerformed
        // TODO add your handling code here:
        this.changePseudo();
    }//GEN-LAST:event_PseudoFieldActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        this.saveValues();
        Application.option.save();
        this.setVisible(false);
    }//GEN-LAST:event_SaveActionPerformed

    private void RemoteModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoteModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoteModeActionPerformed

    private void HistoryServerIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryServerIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryServerIPActionPerformed

    private void changePseudo(){
        //Try to change pseudo
        String pseudo = this.PseudoField.getText();
        int returnValue = this.c.changePseudo(pseudo);
        
        //Analyze the result
        if(returnValue == 1){
            this.AlreadyTakenNameLabel.setText("\""+pseudo+"\" est déjà pris");
        }else if(returnValue == 2){
            this.AlreadyTakenNameLabel.setText("Erreur lors de la notification des utilisateurs");
        }
        
        //Show the comment if necessary
        if(returnValue != 0){
            this.AlreadyTakenNameLabel.setVisible(true);
        }
        else{
            this.AlreadyTakenNameLabel.setVisible(false);
        }

    }
    
    private void prefillForm(){
        Parameter p;
        if((p = Application.option.get("pseudo")) != null)
            this.PseudoField.setText(p.value);
        if((p = Application.option.get("historyPath")) != null)
            this.HistoryPath.setText(p.value);
        if((p = Application.option.get("historyAddr")) != null)
            this.HistoryServerIP.setText(p.value);
        if((p = Application.option.get("remoteAddr")) != null)
            this.RemoteIP.setText(p.value);
        if((p = Application.option.get("remoteMode")) != null)
            this.RemoteMode.setSelected(p.value.equals("true"));
    }
    
    private void saveValues(){
        Application.option.add(new Parameter("pseudo",this.PseudoField.getText()));
        if(!this.HistoryPath.getText().equals("Valeur par défaut"))
            Application.option.add(new Parameter("historyPath",this.HistoryPath.getText()));
        Application.option.add(new Parameter("historyAddr",this.HistoryServerIP.getText()));
        Application.option.add(new Parameter("remoteAddr",this.RemoteIP.getText()));
        Application.option.add(new Parameter("remoteMode",this.RemoteMode.isSelected()+""));
      //  Application.option.save();
    }
    
    /**
     * @param args the command line arguments
     */
    public void open() {
        this.jScrollPane1.getViewport().setOpaque(false);
        
        this.AlreadyTakenNameLabel.setVisible(false);
        this.PseudoField.setText(this.c.getPseudo());
        
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlreadyTakenNameLabel;
    private javax.swing.JLabel ChangeConsideredAtReboot;
    private javax.swing.JTextField HistoryPath;
    private javax.swing.JTextField HistoryServerIP;
    private javax.swing.JButton PseudoCheckBttn;
    private javax.swing.JTextField PseudoField;
    private javax.swing.JTextField RemoteIP;
    private javax.swing.JCheckBox RemoteMode;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
