/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author corentin
 */
public class OptionPage extends javax.swing.JFrame {
    private Controller c;

    /**
     * Creates new form OptionPage
     */
    public OptionPage(Controller c) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        this.c = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PseudoField = new javax.swing.JTextField();
        PseudoCheckBttn = new javax.swing.JButton();
        AlreadyTakenNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HistoryPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("ClavardApp - Paramètres");
        setResizable(false);

        jLabel2.setText("Pseudo de session");

        PseudoField.setText("Pseudo");
        PseudoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoFieldActionPerformed(evt);
            }
        });

        PseudoCheckBttn.setText("Vérifier");
        PseudoCheckBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoCheckBttnActionPerformed(evt);
            }
        });

        AlreadyTakenNameLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AlreadyTakenNameLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));
        AlreadyTakenNameLabel.setText("\"Pseudo\" est déjà pris");

        jLabel3.setText("Lien de sauvegarde de l'historique");

        HistoryPath.setText("Valeur par défaut");
        HistoryPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AlreadyTakenNameLabel))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PseudoField, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PseudoCheckBttn))
                    .addComponent(jLabel3)
                    .addComponent(HistoryPath))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PseudoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PseudoCheckBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlreadyTakenNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HistoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Options");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PseudoCheckBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoCheckBttnActionPerformed
        // TODO add your handling code here:
        this.changePseudo();
    }//GEN-LAST:event_PseudoCheckBttnActionPerformed

    private void HistoryPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryPathActionPerformed

    private void PseudoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoFieldActionPerformed
        // TODO add your handling code here:
        this.changePseudo();
    }//GEN-LAST:event_PseudoFieldActionPerformed

    private void changePseudo(){
        //Try to change pseudo
        String pseudo = this.PseudoField.getText();
        int returnValue = this.c.changePseudo(pseudo);
        
        //Analyze the result
        if(returnValue == 1){
            this.AlreadyTakenNameLabel.setText("\""+pseudo+"\" est déjà pris");
        }else if(returnValue == 2){
            this.AlreadyTakenNameLabel.setText("Erreur lors de la notification des utilisateurs");
        }
        
        //Show the comment if necessary
        if(returnValue != 0){
            this.AlreadyTakenNameLabel.setVisible(true);
        }
        else{
            this.AlreadyTakenNameLabel.setVisible(false);
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public void open() {
        this.jScrollPane1.getViewport().setOpaque(false);
        
        this.AlreadyTakenNameLabel.setVisible(false);
        this.PseudoField.setText(this.c.getPseudo());
        
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlreadyTakenNameLabel;
    private javax.swing.JTextField HistoryPath;
    private javax.swing.JButton PseudoCheckBttn;
    private javax.swing.JTextField PseudoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
